# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

# Seems to be necessary with devtools 1.10.0, check again when the next version is on CRAN
r_github_packages:
  - hadley/testthat

after_success:
  - Rscript -e "devtools::install_github('jimhester/covr'); covr::codecov(exclusions=c('src/sqlite3.c', 'src/extension-functions.c'))"

notifications:
  email:
    on_success: change
    on_failure: change
