# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

matrix:
  - branches:
      except:
        - feature/upgrade-sqlite

    # Seems to be necessary with devtools 1.10.0, check again when the next version is on CRAN
    r_github_packages:
      - hadley/testthat

    after_success:
      - Rscript -e "devtools::install_github('jimhester/covr'); covr::codecov(exclusions=c('src/sqlite3.c', 'src/extension-functions.c'))"

  - branches:
      only:
        - feature/upgrade-sqlite

    before_install: # decrypt deploy key for feature/upgrade-sqlite branch
      - openssl aes-256-cbc -K $encrypted_c3ad55031ba5_key -iv $encrypted_c3ad55031ba5_iv -in .ssh/id_rsa.enc -out .ssh/id_rsa -d; ls .ssh; fi

    install:
      - true

    r_packages:
      - xml2
      - rvest
      - git2r

    script:
      - R -f src-raw/upgrade.R

notifications:
  email:
    on_success: change
    on_failure: change
